version: '2'

# docker-compose up -d
# docker exec -t -i nginx_ssl sh

services:
    nginx:
        build: ./images/nginx
        container_name: nginx_ssl
        ports:
            - "81:80"
            - "8081:80"
            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        links:
            - php
    php:
        build: ./images/php
        container_name: mk_php
        links:
            - mysql
        volumes:
            - ./www:/var/www
    mysql:
        container_name: mk_mysql
        image: mysql:8
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
